version: '3.8'

services:
  frontend:
    build:
      context: ./nightmare-app-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./nightmare-app-backend
    ports:
      - "3001:3000"
    environment:
      - RAILS_ENV=development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: